### ISSUE TITLE
Implement support for implicit pairs

### ISSUE THREAD

**Issue by nvtaveras** [celo-org/celo-oracle#11]
**Reason for need:** we are beholden to centralized exchanges (2) listing CELO pairs against currencies before we can turn on oracles for new stablecoins. Needed for more independent launch of next stablecoin.

**Comment by pedro-clabs** [comment]
Work involves:
 - adding a new PriceSource interface/concept;
 - implementing a multi-exchange price source, that calculates rates implied from multiple pairs;
 - change data aggregator so that it uses PriceSources instead of ExchangeAdapters;
 - add envvar parsing of a price sources variable.
