### ISSUE TITLE
Remove timer-based reporting and trade-based aggregation

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-oracle#15]
### Expected Behavior

Remove timer-based reporting and trade based aggregation. We should probably keep things set up in a way where we can easily add a new report or aggregation strategy in the future, but there is no need to keep code around that isn't used at all.

### Current Behavior

When we transitioned to block-based reporting and a ticker-based price aggregation, we kept the code for timer-based reporting and ticker-based aggregation so we could easily revert back if we wanted to. Now that we've been running the oracles with the current setup for many months, the unused code is tech debt, a burden to maintain, and has some confusing unused config variables

**Comment by albertclabs** [comment]
This blocks implicit pairs work.
