### ISSUE TITLE
CELO/BTC Oracle on Celo deployed to Mainnet

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-oracle#22]
Part of this needs to resolve the legal considerations. We don't guarantee the prices and people choose to use them at will.

Out of scope:
- HSM setup
- Governance proposal to whitelist the oracles for CELO/BTC

**Comment by albertclabs** [comment]
@albertclabs will check in with Keep whether we can test this on Baklava

**Comment by nvtaveras** [comment]
no longer relevant
